import { Geist, Geist_Mono, Rajdhani, Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/redux/StoreProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const fontTitle = Rajdhani({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-title",
});

const fontBody = Inter({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-body",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html
			suppressHydrationWarning
			lang="en"
			className={`${fontTitle.variable} ${fontBody.variable} scroll-smooth scroll-pt-36`}
		>
			<body className="font-txtFont flex flex-col">
				<StoreProvider>
					<main className="overflow-hidden">
						<Navbar />
						{children}
						<Footer />
					</main>
				</StoreProvider>
			</body>
		</html>
	);
}
